# Generated by Django 3.2.3 on 2021-05-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Баланс'),
        ),
    ]
