# Generated by Django 3.2.3 on 2021-05-22 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
