# Generated by Django 3.1.8 on 2021-07-25 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0003_auto_20210725_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.CharField(default=228, max_length=250),
            preserve_default=False,
        ),
    ]
