# Generated by Django 3.1.8 on 2021-07-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_asset_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='icon',
            field=models.FileField(null=True, upload_to='stocks_icon', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='sector',
            field=models.CharField(max_length=150, null=True, verbose_name='Сектор'),
        ),
    ]
