# Generated by Django 3.1.8 on 2021-07-25 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0005_auto_20210725_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('no_type', ' Без типа'), ('Stock', 'акции/облигации'), ('Crypto', 'токен')], default='no_type', max_length=20, verbose_name='Тип актива'),
        ),
    ]
