# Generated by Django 3.1.8 on 2021-07-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0006_auto_20210725_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
