# Generated by Django 3.1.8 on 2021-07-31 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0007_asset_price_json'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='profile',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='profile',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='invest.profile', verbose_name='Профиль'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Сумма'),
        ),
    ]
