# Generated by Django 3.1.8 on 2021-07-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0009_auto_20210731_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, null=True, verbose_name='Сумма'),
        ),
    ]
