# Generated by Django 3.1.8 on 2021-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0010_item_purchase_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='asset',
        ),
        migrations.AddField(
            model_name='item',
            name='asset',
            field=models.ManyToManyField(to='invest.Asset'),
        ),
    ]
