# Generated by Django 3.2.3 on 2021-05-27 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0003_auto_20210525_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealhistory',
            name='items',
            field=models.ManyToManyField(null=True, related_name='deal_assets', to='finances.Item', verbose_name='Предметы сделки'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.RemoveField(
            model_name='dealhistory',
            name='deal_owner',
        ),
        migrations.AddField(
            model_name='dealhistory',
            name='deal_owner',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='deal_owner', to='login_system.user', verbose_name='Иннициатор сделки'),
            preserve_default=False,
        ),
    ]
