# Generated by Django 3.1.8 on 2021-07-12 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login_system', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='stocks_icon', verbose_name='Изображение')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование актива')),
                ('ticker', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Тикер актива')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость актива')),
                ('type', models.CharField(choices=[('no_type', ' Без типа'), ('stock', 'акции/облигации'), ('crypto', 'токен')], default='no_type', max_length=20, verbose_name='Тип актива')),
                ('sector', models.CharField(max_length=150, null=True, verbose_name='Сектор')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Количество ')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='finances.asset')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма')),
                ('items', models.ManyToManyField(null=True, related_name='assets', to='finances.Item', verbose_name='Активы')),
                ('profile', models.ManyToManyField(related_name='profile', to='login_system.Profile', verbose_name='Профиль')),
            ],
        ),
        migrations.CreateModel(
            name='DealHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('deal_type', models.CharField(choices=[('no_type', ' Без типа'), ('buy_stock', 'Покупка акции/облигации'), ('buy_crypto', 'Покупка токенизированных активов'), ('sell_stock', 'Продажа акции/облигации'), ('sell_crypto', 'Продажа токенизированных активов'), ('exchange', 'Обмен')], default='no_type', max_length=20, verbose_name='Тип сделки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость актива')),
                ('status', models.CharField(choices=[('started', ' Начало'), ('not_paid', 'Не оплачена'), ('awaiting_payment', 'Ожидает оплаты'), ('canceled', 'Отменена'), ('ended', 'Завершена')], default='started', max_length=40, verbose_name='Тип сделки')),
                ('deal_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_owner', to=settings.AUTH_USER_MODEL, verbose_name='Иннициатор сделки')),
                ('dealers', models.ManyToManyField(related_name='dealers', to=settings.AUTH_USER_MODEL, verbose_name='Участник(и) сделки')),
                ('items', models.ManyToManyField(null=True, related_name='deal_assets', to='finances.Item', verbose_name='Предметы сделки')),
            ],
        ),
    ]
