# Generated by Django 3.2.3 on 2021-05-22 07:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование актива')),
                ('ticker', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тикер актива')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость актива')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Сумма')),
                ('assets', models.ManyToManyField(related_name='assets', to='finances.Asset', verbose_name='Активы')),
                ('profile', models.ManyToManyField(related_name='profile', to='login_system.Profile', verbose_name='Профиль')),
            ],
        ),
        migrations.CreateModel(
            name='DealHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(auto_now_add=True)),
                ('deal_type', models.CharField(choices=[('no_type', ' Без типа'), ('buy_stock', 'Покупка акции/облигации'), ('buy_crypto', 'Покупка токенизированных активов'), ('sell_stock', 'Продажа акции/облигации'), ('sell_crypto', 'Продажа токенизированных активов'), ('exchange', 'Обмен')], default='no_type', max_length=20, verbose_name='Тип сделки')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Стоимость актива')),
                ('deal_owner', models.ManyToManyField(related_name='deal_owner', to=settings.AUTH_USER_MODEL, verbose_name='Участник(и) сделки')),
                ('dealers', models.ManyToManyField(related_name='dealers', to=settings.AUTH_USER_MODEL, verbose_name='Участник(и) сделки')),
            ],
        ),
    ]
