# Generated by Django 3.1.8 on 2021-07-12 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='icon',
            field=models.FileField(null=True, upload_to='stocks_icon', verbose_name='Изображение'),
        ),
    ]
