# Generated by Django 3.2.3 on 2021-05-25 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='count',
        ),
        migrations.RemoveField(
            model_name='portfolio',
            name='assets',
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('no_type', ' Без типа'), ('stock', 'Покупка акции/облигации'), ('crypto', 'Покупка токенизированных активов')], default='no_type', max_length=20, verbose_name='Тип сделки'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='ticker',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Тикер актива'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField(verbose_name='Количество ')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='finances.asset')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='items',
            field=models.ManyToManyField(null=True, related_name='assets', to='finances.Item', verbose_name='Активы'),
        ),
    ]
