# Generated by Django 3.2.3 on 2021-05-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_auto_20210525_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asset',
            name='type',
            field=models.CharField(choices=[('no_type', ' Без типа'), ('stock', 'акции/облигации'), ('crypto', 'токен')], default='no_type', max_length=20, verbose_name='Тип актива'),
        ),
    ]
